language: nix
matrix:
  include:
    - os: osx
      osx_image: xcode8.3  # 10.12
    - os: linux

install:
   - nix-env -iA nixpkgs.emacs
   - mkdir -p ~/.emacs.d && curl -sSL https://raw.githubusercontent.com/hniksic/emacs-htmlize/master/htmlize.el --output ~/.emacs.d/htmlize.el

script:
  - nix build
  - ./result/bin/dotfiles install
  - ./result/bin/dotfiles link
  - ./result/bin/dotfiles uninstall

after_success:
  - git tag "${date +"%F-%T}" -m "🚀️ ship it"
  - cd docs && emacs -Q index.org --batch --eval "(progn (load \"~/.emacs.d/htmlize.el\")(org-babel-tangle)(org-html-export-to-html))" --kill

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  target-branch: gh-pages
  fqdn: dotfiles.codearsonist.com
  on:
    branch: master
