language: generic
os:
  - osx

sudo: required

before-install:
  - brew update
  - brew tap Homebrew/bundle

install:
  - brew uninstall git 
  - brew uninstall tmux

script:
  - make brew
  - make brew-minimal
  - make osx
  - make editor
  - make link 
  - make clean
