language: generic
os:
  - osx

sudo: required

before-install:
  - brew update
  - brew tap Homebrew/bundle

install:
  - brew install stow
  - brew install fish

script:
  - make osx
  - make editor
  - make link 
  - make clean
