language: generic
os:
  - osx

sudo: required

before-install:
  - brew update
  - brew tap Homebrew/bundle

install:
  - brew instal make
  - brew install ruby
  - brew install stow

script:
  - make utils
  - make link 
