language: nix
matrix:
  include:
    - os: osx
      osx_image: xcode8.3  # 10.12
    - os: linux
script:
  - nix build
  - ./result/bin/dotfiles install
  - ./result/bin/dotfiles link
  - ./result/bin/dotfiles uninstall